In [1]:
import numpy as np

In [10]:
a=np.array([[[1,2],[3,4],[1,2]],[[2,3],[2,6],[2,3]]])

In [11]:
a.ndim

3

In [ ]:
b=np.array([[]])

In [12]:
a.shape

(2, 3, 2)

In [20]:
b=np.arange(1,10,3)

In [21]:
b

array([1, 4, 7])

In [18]:
c=np.linspace(1,100,20)

In [19]:
c

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [22]:
x=np.array([1,2,3,4])
y=np.array([3,4,5,6])

In [23]:
x+y

array([ 4,  6,  8, 10])

# Broadcasting

In [48]:
a=np.array([[[1,2,3,3],[1,2,2,3]],[[1,2,2,3],[1,2,3,3]],[[1,2,3,4],[1,2,3,5]]])
b=np.array([[1,2,3,2],[1,2,3,4]])

In [46]:
b.shape

(2, 4)

In [49]:
a+b

array([[[2, 4, 6, 5],
        [2, 4, 5, 7]],

       [[2, 4, 5, 5],
        [2, 4, 6, 7]],

       [[2, 4, 6, 6],
        [2, 4, 6, 9]]])

# Where operation

In [51]:
print(np.where(a==3))

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64), array([0, 0, 1, 0, 1, 1, 0, 1], dtype=int64), array([2, 3, 3, 3, 2, 3, 2, 2], dtype=int64))


In [52]:
print(np.where(a%2==0))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 1, 0, 0, 1, 0, 0, 1], dtype=int64), array([1, 1, 2, 1, 2, 1, 1, 3, 1], dtype=int64))


In [58]:
print(np.where((a<5)&(a>2)))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 0, 1, 0, 1, 1, 0, 0, 1], dtype=int64), array([2, 3, 3, 3, 2, 3, 2, 3, 2], dtype=int64))


In [61]:
np.sort(a,kind="merge")

array([[[1, 2, 3, 3],
        [1, 2, 2, 3]],

       [[1, 2, 2, 3],
        [1, 2, 3, 3]],

       [[1, 2, 3, 4],
        [1, 2, 3, 5]]])

In [62]:
np.sort(a,kind="quick")

array([[[1, 2, 3, 3],
        [1, 2, 2, 3]],

       [[1, 2, 2, 3],
        [1, 2, 3, 3]],

       [[1, 2, 3, 4],
        [1, 2, 3, 5]]])